name: Build, Test, Lint for Pull Requests

on:
  workflow_call:

jobs:
  setup:
    name: Setup, Build, Lint and Test
    permissions:
      pull-requests: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Echo
        run: echo Hello
