name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  first:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ qwe, rty, uio ]
    steps:
      - name: Checkout (including submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Create file
        run: |
          mkdir datadir
          cd datadir
          echo "${{ matrix.platform }} https://${{ matrix.platform }}.com" > ${{ matrix.platform }}.txt
      - uses: actions/upload-artifact@v3
        with:
          path: datadir/${{ matrix.platform }}.txt
  second: 
    runs-on: ubuntu-latest
    needs: first
    permissions:
      pull-requests: write
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Download file
        uses: actions/download-artifact@master
        with:
          path: datadir
      - name: Format
        run: |
          echo '## :fire: End To End Tests Report :fire:' > comment.txt
          cd datadir/artifact/
          declare -a artifacts=(*)
          for artifact in "${artifacts[@]}"; do
            declare suite=$(cat ${artifact} | cut -d ' ' -f1)
            declare link=$(cat ${artifact} | cut -d ' ' -f2)
            echo "* [${suite}](${link})" >> ${{ github.workspace }}/comment.txt
          done
      - name: Add test report comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: comment.txt
          reactions: eyes
          mode: recreate
          comment_tag: test_report
