name: Test Workflow Listener

on:
  pull_request:
    types: [labeled]
    branches:
      - main

jobs:
  on-label:
    permissions:
      pull-requests: write
    uses: uarlouski/quick-check/.github/workflows/build-test-lint-simple.yml@main
    secrets: inherit
    if: ${{ github.event.label.name == 'ready-to-test' || github.event.label.name == 'skip-tests' }}
